mysql:
  prefix: core-
  host: localhost
  port: 3306
  user: root
  pass: domiS2002_!
  name: blazepe
check_allowed_commands:
  - wyslij
  - helpop
config:
  blocked:
    cmd:
      incombat:
        - baza
        - os
        - achievements
        - osiagniecia
        - warp
        - depozyt
        - czas
        - kit
        - spawn
        - home
        - sethome
        - tpa
        - tpaccept
        - tpdeny
        - repair
        - schowek
        - crafting
        - enderchest
        - gildia dom
        - g dom
        - ec
        - schowek
        - depozyt
        - repair all
limit:
  kox: 1
  refy: 8
  perly: 3
automsg:
  - '&7testowa'
  - '&ctestowa2'
wl:
  motd: '&3xxx.pl'
  enable: true
  list:
    - VerttyPL
  reason: '&cTrwaja prace techniczne!'
border: 800
borderd: 800.0
slowmode: 5
unknown-command: '&cNie odnaleziono takiej komendy na serwerze &6/pomoc'
format:
  global: '&7{POINTS} {PREFIX}{RANGA} &7{PLAYER} &8>> &r{SUFFIX}{MSG}'
  admin: '{PREFIX}{RANGA} &7{PLAYER} &8>> &r{SUFFIX}{MSG}'
  chat:
    player:
      prefix: '&7'
      suffix: '&7'
      fullname: ''
    vip:
      prefix: '&6'
      suffix: '&7'
      fullname: VIP
    svip:
      prefix: '&e'
      suffix: '&7'
      fullname: SVIP
    yt:
      prefix: '&5'
      suffix: '&7'
      fullname: YOUTUBER
    sponsor:
      prefix: '&3'
      suffix: '&7'
      fullname: SPONSOR
    helper:
      prefix: '&3'
      suffix: '&b'
      fullname: HELPER
    moderator:
      prefix: '&2'
      suffix: '&a'
      fullname: MODERATOR
    admin:
      prefix: '&c'
      suffix: '&e'
      fullname: ADMIN
    headadmin:
      prefix: '&c'
      suffix: '&6'
      fullname: HEADADMIN
    root:
      prefix: '&4'
      suffix: '&6'
      fullname: ROOT
pomoc: "TEST{N}TEST"
vip: "TEST{N}TEST"
svip: "TEST{N}TEST"
sponsor: "TEST{N}TEST"
yt: "TEST{N}TEST"